### ISSUE TITLE
need post request schema (request body items)

### ISSUE THREAD

**Issue by soragpt** [bincooo/single-proxy#1]
Hi [bincooo](https://github.com/bincooo),
please tell me post request schema (request body items need)
waiting for your response
regards

**Comment by bincooo** [comment]
This program does not do the http request type routing forward, only for the path to do the forward. So, whether you're a get or a post, it will be executed:
```
mappers:
  - addr: https://api.openai.com
    routes:
      - path: /proxies/v1/*
        rewrite: /v1/$1
```

The above example, you can send a "POST" request to the`/proxies/v1/chat/complations`, also can send a "GET" request to`/proxies/v1/models`.  It will eventually rewrite your path to `/v1/chat/complations` and `/v1/models`.

What do you want to do with it?
